project:
  type: website
  output-dir: docs
website:
  title: "Lucas Castillo"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme:
      light: cosmo
    css: styles.css
    toc: true

editor: visual

