project:
  type: website
  output-dir: docs
website:
  title: "Lucas Castillo"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - href: files/CV.pdf
        text: CV

format:
  html:
    theme:
      light: cosmo
    css: styles.css
    toc: true
