project:
  type: website
  output-dir: docs
website:
  title: "Lucas Castillo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      # - href: blog.qmd
    right:
      - href: files/CV.pdf
        text: CV
    search: false
  favicon: images/logo.png

format:
  html:
    theme:
      light: cosmo
    css: styles.css
    toc: true
